name: algorithms
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.1
